#!/usr/bin/env python3

# Copyright (C) 2020-2021 Gabriele Bozzola
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/>.

"""Visualize 2D grid data, centered on the first apparent horizon, and optionally drawing the horizons.
"""

from matplotlib.pyplot import clf as clear_figure
from kuibit import argparse_helper as kah
from kuibit.simdir import SimDir
from kuibit.visualize_matplotlib import (
    add_text_to_corner,
    plot_color,
    plot_horizon_on_plane_at_iteration,
    save,
    setup_matplotlib,
)
import numpy as np


def mopi_add_custom_options(parser):
    # These are the custom options that mopi will see.

    parser.add_argument("--datadir", default=".", help="Data directory.")
    kah.add_horizon_to_parser(parser)
    parser.add_argument(
        "--ignore-symlinks",
        action="store_true",
        help="Ignore symlinks in the data directory",
    )
    kah.add_grid_to_parser(parser, dimensions=2)
    kah.add_figure_to_parser(parser)
    parser.add_argument(
        "--variable", type=str, required=True, help="Variable to plot."
    )
    parser.add_argument(
        "--multilinear-interpolate",
        action="store_true",
        help="Whether to interpolate to smooth data with multilinear"
        " interpolation before plotting.",
    )
    parser.add_argument(
        "--interpolation-method",
        type=str,
        default="none",
        help="Interpolation method for the plot. See docs of np.imshow."
        " (default: %(default)s)",
    )
    parser.add_argument(
        "--colorbar",
        action="store_true",
        help="Whether to draw the color bar.",
    )
    parser.add_argument(
        "--logscale",
        action="store_true",
        help="Whether to use log scale.",
    )
    parser.add(
        "--vmin",
        help=(
            "Minimum value of the variable. "
            "If logscale is True, this has to be the log. "
        ),
        type=float,
    )
    parser.add(
        "--vmax",
        help=(
            "Maximum value of the variable. "
            "If logscale is True, this has to be the log."
        ),
        type=float,
    )
    parser.add_argument(
        "--absolute",
        action="store_true",
        help="Whether to take the absolute value.",
    )


class MOPIMovie:
    def __init__(self, args):
        # Here we initialize all the objects that we need for all the frames.
        # All the expensive stuff has to be done here.

        # TODO: Automatically compute min and max if they are not specified.

        self.sim = SimDir(args.datadir, ignore_symlinks=args.ignore_symlinks)
        self.x0, self.x1, self.res = args.origin, args.corner, args.resolution
        self.shape = [self.res, self.res]
        self.reader = self.sim.gridfunctions[args.plane]
        self.var = self.reader[args.variable]

        self.iterations = self.var.available_iterations

        # get centroid timeseries
        self.horizon = self.sim.horizons[0, 1]
        self.centroid_x = self.horizon.ah.centroid_x
        self.centroid_y = self.horizon.ah.centroid_y
        self.centroid_z = self.horizon.ah.centroid_z


        # Apparent horizons
        self.ahs = {}

        if args.ah_show:
            for ah in self.sim.horizons.available_apparent_horizons:
                self.ahs[ah] = self.sim.horizons.get_apparent_horizon(ah)

        self.args = args

    def get_frames(self):
        # Here we define what is a "frame" (it is one iteration). This function
        # has to return an iterable on what we want to make frames of.
        return self.iterations

    def make_frame(self, path, iteration):
        # Here we plot a frame. This function has to take the output path and
        # the identifier of what is a frame (in this case, an iteration).

        setup_matplotlib()
        clear_figure()

        # TODO: check that I actually want the following settings:
        #Gonna override some things:
        #matplotlib.rcParams.update(
        #{
        #    "lines.markersize": 4,
        #    "axes.labelsize": 16,
        #    "font.weight": "light",
        #    "font.size": 16,
        #    "legend.fontsize": 16,
        #    "xtick.labelsize": 13,
        #    "ytick.labelsize": 13,
        #    "axes.formatter.limits": [-3, 3],
        #    "xtick.minor.visible": True,
        #    "ytick.minor.visible": True,
        #    "image.cmap": "PuRd",
        #}
        #)

        if self.args.absolute:
            data = abs(self.var[iteration])
            variable = f"abs({self.args.variable})"
        else:
            data = self.var[iteration]
            variable = self.args.variable

        if self.args.logscale:
            label = f"log10({variable})"
        else:
            label = variable
        # Find the time for this iteration:
        time = self.var.time_at_iteration(iteration)
        # Interpolate the x & y bh centroid time series to that time
        # To recover the bh x & y position at this time
        if (self.args.plane == "xy"):
            bh_coord_1 = self.centroid_x(time)
            bh_coord_2 = self.centroid_y(time)
        elif (self.args.plane == "xz"):
            bh_coord_1 = self.centroid_x(time)
            bh_coord_2 = self.centroid_z(time)
        elif (self.args.plane == "yz"):
            bh_coord_1 = self.centroid_y(time)
            bh_coord_2 = self.centroid_z(time)
        else:
            print("Uh-oh, this type of grid isn't supported by ah tracking.")
            bh_coord_1 = 0.
            bh_coord_2 = 0.
        # Shift x0 and x1 by the appropriate amount given the bh centroids
        plot_color(
            data,
            x0=np.array([self.x0[0]+bh_coord_1, self.x0[1]+bh_coord_2]),
            x1=np.array([self.x1[0]+bh_coord_1, self.x1[1]+bh_coord_2]),
            shape=self.shape,
            xlabel=self.args.plane[0],
            ylabel=self.args.plane[1],
            resample=self.args.multilinear_interpolate,
            colorbar=self.args.colorbar,
            logscale=self.args.logscale,
            vmin=self.args.vmin,
            vmax=self.args.vmax,
            label=label,
            interpolation=self.args.interpolation_method,
        )
        # TODO: some plot transforms magic to stop video from jittering and
        # stop the axes from shifting (see old archived code) 

        # TODO: Replace this with something using shape_outline_at_time so that
        # it can interpolate to the closest time rather than strictly using
        # the current iteration
        if self.args.ah_show:
            for hor in self.ahs.values():
                # Check if we have the shape at the current iteration
                if iteration in hor.shape_iterations:
                    plot_horizon_on_plane_at_iteration(
                        hor,
                        iteration,
                        self.args.plane,
                        color=self.args.ah_color,
                        edgecolor=self.args.ah_edge_color,
                        alpha=self.args.ah_alpha,
                    )

        # Below is what was done previously. I remember it kinda worked:
        ## Get horizon shape
        #if self.args.ah_show:
        #    shape = self.horizon.shape_outline_at_time(time, (None, None, 0))
        #    plt.gca().fill(shape[0], shape[1], self.args.ah_color)

        time = self.var.time_at_iteration(iteration)
        add_text_to_corner(fr"$t = {time:.3f}$")

        save(path)
